using BiatecTokensApi.Models.ProtectedSignOff;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using NUnit.Framework;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace BiatecTokensTests
{
    /// <summary>
    /// End-to-end integration tests for the protected strict sign-off journey.
    ///
    /// These tests are the canonical in-process evidence that the backend-managed
    /// issuance critical path works in a fail-closed manner.  Each test drives the
    /// full journey via HTTP through a <see cref="WebApplicationFactory{TEntryPoint}"/>
    /// — from email/password authentication through environment readiness, fixture
    /// provisioning, lifecycle verification, and diagnostics — and produces a structured
    /// evidence manifest that mirrors the artifact generated by the Tier 2 CI workflow.
    ///
    /// Coverage:
    ///
    /// E2E01: Full happy path — authenticate → environment check → fixture provision →
    ///        lifecycle execute → diagnostics → evidence manifest construction succeeds.
    /// E2E02: Lifecycle reaches Complete stage and IsLifecycleVerified=true (release gate criterion).
    /// E2E03: Environment check after fixture provisioning returns Ready status and IsReadyForProtectedRun=true.
    /// E2E03b: Environment check with config-check-only scope returns Ready without requiring fixtures.
    /// E2E04: Fixture provision returns IsProvisioned=true and correct issuer ID.
    /// E2E05: Diagnostics returns IsOperational=true with no configuration failures.
    /// E2E06: Evidence manifest fields are populated and parseable (CorrelationId, RunAt, results).
    /// E2E07: Happy path is deterministic — identical results across 3 independent runs.
    /// E2E08: Authentication failure (wrong password) is distinguishable from backend unavailability.
    /// E2E09: Lifecycle correctly fails and attributes the failure when initiation prerequisites are absent.
    /// E2E10: Missing-config backend returns Misconfigured environment status (fail-closed).
    /// E2E11: All 6 lifecycle stages appear in expected order with correct outcomes.
    /// E2E12: Every Verified stage has null UserGuidance (evidence is clean, no operator noise).
    /// E2E13: CorrelationId supplied in request is echoed across all four response objects.
    /// E2E14: Environment check WorkflowGovernanceEnabled check is observable from response.
    /// E2E15: Full journey is independently repeatable — concurrent users share no mutable state.
    /// E2E16: Fixture reset produces a consistent provisioned issuer ID across calls.
    /// E2E17: Environment check without prior fixture provision still returns a fixture status check.
    /// E2E18: All lifecycle stage results have non-null, concrete outcome values.
    /// E2E19: Diagnostics distinguishes configuration failures from service failures (FailureCategories).
    /// E2E20: Release gate predicate IsLifecycleVerified=true holds for a well-configured environment.
    /// </summary>
    [TestFixture]
    [NonParallelizable]
    public class ProtectedSignOffEndToEndTests
    {
        // ── Evidence manifest record (mirrors Tier 2 CI workflow artifact schema) ─────

        /// <summary>
        /// Structured evidence manifest constructed from the four API responses.
        /// This is the in-process equivalent of the <c>00_evidence_manifest.json</c>
        /// artifact produced by the Tier 2 <c>protected-sign-off-run</c> CI job.
        /// </summary>
        private sealed record EvidenceManifest(
            string CorrelationId,
            string RunAt,
            string EnvironmentLabel,
            string EnvironmentStatus,
            bool IsReadyForProtectedRun,
            bool FixturesProvisioned,
            bool LifecycleVerified,
            string ReachedStage,
            bool DiagnosticsOperational,
            string ObservedGovernanceCheckOutcome);

        // ── WebApplicationFactory ─────────────────────────────────────────────────────

        private SignOffFactory _factory = null!;
        private HttpClient _client = null!;
        private string _jwt = null!;
        private const string CorrelationBase = "e2e-protected-run";

        [SetUp]
        public async Task SetUp()
        {
            _factory = new SignOffFactory();
            _client = _factory.CreateClient();
            _jwt = await ObtainJwtAsync(_client, $"e2e-{Guid.NewGuid():N}");
            _client.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _jwt);
        }

        [TearDown]
        public void TearDown()
        {
            _client.Dispose();
            _factory.Dispose();
        }

        // ── E2E01: Full happy path produces a valid evidence manifest ─────────────────

        [Test]
        public async Task E2E01_FullHappyPath_ProducesValidEvidenceManifest()
        {
            string corr = $"{CorrelationBase}-e2e01-{Guid.NewGuid():N}";

            // 1. Fixture provision (must run before environment check so fixture check passes)
            EnterpriseFixtureProvisionResponse fixtureResp = await PostFixtureProvisionAsync(_client, corr);
            Assert.That(fixtureResp, Is.Not.Null, "Fixture provision must return a response");

            // 2. Environment check (after fixture provision, all checks should pass)
            ProtectedSignOffEnvironmentResponse envResp = await PostEnvironmentCheckAsync(_client, corr);
            Assert.That(envResp, Is.Not.Null, "Environment check must return a response");

            // 3. Lifecycle execute
            EnterpriseSignOffLifecycleResponse lifecycleResp = await PostLifecycleExecuteAsync(_client, corr);
            Assert.That(lifecycleResp, Is.Not.Null, "Lifecycle execute must return a response");

            // 4. Diagnostics
            ProtectedSignOffDiagnosticsResponse diagResp = await GetDiagnosticsAsync(_client, corr);
            Assert.That(diagResp, Is.Not.Null, "Diagnostics must return a response");

            // 5. Build evidence manifest (mirrors Tier 2 CI artifact schema)
            string govOutcome = envResp.Checks
                .FirstOrDefault(c => c.Name == "WorkflowGovernanceEnabled")
                ?.Outcome.ToString() ?? "NotChecked";

            EvidenceManifest manifest = new(
                CorrelationId: corr,
                RunAt: DateTime.UtcNow.ToString("O"),
                EnvironmentLabel: "in-process-e2e",
                EnvironmentStatus: envResp.Status.ToString(),
                IsReadyForProtectedRun: envResp.IsReadyForProtectedRun,
                FixturesProvisioned: fixtureResp.IsProvisioned,
                LifecycleVerified: lifecycleResp.IsLifecycleVerified,
                ReachedStage: lifecycleResp.ReachedStage.ToString(),
                DiagnosticsOperational: diagResp.IsOperational,
                ObservedGovernanceCheckOutcome: govOutcome);

            Assert.Multiple(() =>
            {
                Assert.That(manifest.CorrelationId, Is.EqualTo(corr),
                    "Evidence manifest must carry the request correlation ID");
                Assert.That(manifest.RunAt, Is.Not.Null.And.Not.Empty,
                    "Evidence manifest must have a non-empty run timestamp");
                Assert.That(manifest.LifecycleVerified, Is.True,
                    "Lifecycle must be verified — this is the release-gate criterion");
                Assert.That(manifest.ReachedStage, Is.EqualTo("Complete"),
                    "Reached stage must be Complete for a passing protected run");
            });
        }

        // ── E2E02: Lifecycle reaches Complete and IsLifecycleVerified=true ───────────

        [Test]
        public async Task E2E02_LifecycleExecute_ReachesCompleteStage_WithVerifiedTrue()
        {
            string corr = $"{CorrelationBase}-e2e02";

            EnterpriseSignOffLifecycleResponse resp = await PostLifecycleExecuteAsync(_client, corr);

            Assert.Multiple(() =>
            {
                Assert.That(resp.IsLifecycleVerified, Is.True,
                    "IsLifecycleVerified must be true — this is the Tier 2 release gate check");
                Assert.That(resp.ReachedStage, Is.EqualTo(SignOffLifecycleStage.Complete),
                    "ReachedStage must be Complete for a passing protected run");
                Assert.That(resp.FailedStageCount, Is.EqualTo(0),
                    "No stages should fail in the happy path");
                Assert.That(resp.VerifiedStageCount, Is.EqualTo(6),
                    "All 6 lifecycle stages must be verified");
            });
        }

        // ── E2E03: Environment check returns Ready and IsReadyForProtectedRun=true ───
        //
        // Note: the environment check includes a fixture check. Fixtures must be provisioned
        // first (or IncludeFixtureCheck=false) for the status to be Ready. The Tier 2 CI
        // workflow provisions fixtures before calling the full environment check.

        [Test]
        public async Task E2E03_EnvironmentCheck_AfterFixtureProvision_ReturnsReady()
        {
            string corr = $"{CorrelationBase}-e2e03";

            // Provision fixtures first so the fixture check passes
            await PostFixtureProvisionAsync(_client, corr);

            // Now run environment check — all checks should pass
            ProtectedSignOffEnvironmentResponse resp = await PostEnvironmentCheckAsync(_client, corr);

            Assert.Multiple(() =>
            {
                Assert.That(resp.Status, Is.EqualTo(ProtectedEnvironmentStatus.Ready),
                    "Environment status must be Ready after fixture provisioning");
                Assert.That(resp.IsReadyForProtectedRun, Is.True,
                    "IsReadyForProtectedRun must be true when fixtures are provisioned");
                Assert.That(resp.CriticalFailCount, Is.EqualTo(0),
                    "No critical failures should be present in a fully configured environment");
            });
        }

        // ── E2E03b: Environment check with config-only scope returns Ready regardless of fixtures ─

        [Test]
        public async Task E2E03b_EnvironmentCheck_ConfigCheckOnly_ReturnsReady_WithoutFixtures()
        {
            string corr = $"{CorrelationBase}-e2e03b";

            // Check without fixture check — configuration alone should be Ready
            HttpResponseMessage resp = await _client.PostAsJsonAsync(
                "/api/v1/protected-sign-off/environment/check",
                new ProtectedSignOffEnvironmentRequest
                {
                    CorrelationId = corr,
                    IncludeConfigCheck = true,
                    IncludeFixtureCheck = false,    // skip fixture check
                    IncludeObservabilityCheck = false
                });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK));
            ProtectedSignOffEnvironmentResponse? body =
                await resp.Content.ReadFromJsonAsync<ProtectedSignOffEnvironmentResponse>();

            Assert.That(body, Is.Not.Null);
            Assert.Multiple(() =>
            {
                Assert.That(body!.Status, Is.EqualTo(ProtectedEnvironmentStatus.Ready),
                    "Environment status must be Ready when config is present and fixture check is skipped");
                Assert.That(body.IsReadyForProtectedRun, Is.True,
                    "IsReadyForProtectedRun must be true when config check passes");
            });
        }

        // ── E2E04: Fixture provision returns IsProvisioned=true ──────────────────────

        [Test]
        public async Task E2E04_FixtureProvision_ReturnsIsProvisioned_True()
        {
            string corr = $"{CorrelationBase}-e2e04";

            EnterpriseFixtureProvisionResponse resp = await PostFixtureProvisionAsync(_client, corr);

            Assert.Multiple(() =>
            {
                Assert.That(resp.IsProvisioned, Is.True,
                    "Fixture provisioning must succeed for a protected sign-off run");
                Assert.That(resp.IssuerId, Is.Not.Null.And.Not.Empty,
                    "Provisioned issuer ID must be returned in the response");
                Assert.That(resp.CorrelationId, Is.EqualTo(corr),
                    "CorrelationId must be echoed from the request");
            });
        }

        // ── E2E05: Diagnostics returns IsOperational=true, no config failures ────────

        [Test]
        public async Task E2E05_Diagnostics_ReturnsOperational_WithNoConfigFailures()
        {
            string corr = $"{CorrelationBase}-e2e05";

            ProtectedSignOffDiagnosticsResponse resp = await GetDiagnosticsAsync(_client, corr);

            Assert.Multiple(() =>
            {
                Assert.That(resp.IsOperational, Is.True,
                    "Backend must be operational when config is correctly provided");
                Assert.That(resp.FailureCategories.HasConfigurationFailure, Is.False,
                    "No configuration failures expected when all required keys are present");
                Assert.That(resp.ServiceAvailability, Is.Not.Null.And.Not.Empty,
                    "Service availability list must be populated in diagnostics");
            });
        }

        // ── E2E06: Evidence manifest fields are populated and parseable ───────────────

        [Test]
        public async Task E2E06_EvidenceManifest_AllFields_ArePopulated()
        {
            string corr = $"{CorrelationBase}-e2e06";

            // Provision fixtures first so environment check reports Ready
            EnterpriseFixtureProvisionResponse fixtureResp = await PostFixtureProvisionAsync(_client, corr);
            ProtectedSignOffEnvironmentResponse envResp = await PostEnvironmentCheckAsync(_client, corr);
            EnterpriseSignOffLifecycleResponse lifecycleResp = await PostLifecycleExecuteAsync(_client, corr);
            ProtectedSignOffDiagnosticsResponse diagResp = await GetDiagnosticsAsync(_client, corr);

            string govOutcome = envResp.Checks
                .FirstOrDefault(c => c.Name == "WorkflowGovernanceEnabled")
                ?.Outcome.ToString() ?? "NotChecked";

            EvidenceManifest manifest = new(
                CorrelationId: corr,
                RunAt: DateTime.UtcNow.ToString("O"),
                EnvironmentLabel: "in-process-e2e",
                EnvironmentStatus: envResp.Status.ToString(),
                IsReadyForProtectedRun: envResp.IsReadyForProtectedRun,
                FixturesProvisioned: fixtureResp.IsProvisioned,
                LifecycleVerified: lifecycleResp.IsLifecycleVerified,
                ReachedStage: lifecycleResp.ReachedStage.ToString(),
                DiagnosticsOperational: diagResp.IsOperational,
                ObservedGovernanceCheckOutcome: govOutcome);

            // Serialize to verify the manifest is JSON-serializable (as it would be in the CI artifact)
            string json = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });

            Assert.Multiple(() =>
            {
                Assert.That(json, Is.Not.Null.And.Not.Empty,
                    "Evidence manifest must serialize to non-empty JSON");
                Assert.That(json, Does.Contain(corr),
                    "Serialized manifest must contain the correlation ID");
                Assert.That(manifest.EnvironmentStatus, Is.Not.Null.And.Not.Empty,
                    "EnvironmentStatus must be a non-empty string");
                Assert.That(manifest.ReachedStage, Is.Not.Null.And.Not.Empty,
                    "ReachedStage must be a non-empty string");
                Assert.That(manifest.ObservedGovernanceCheckOutcome, Is.Not.Null.And.Not.Empty,
                    "ObservedGovernanceCheckOutcome must be a non-empty string");
                Assert.That(DateTime.TryParse(manifest.RunAt, out _), Is.True,
                    "RunAt must be a parseable timestamp");
            });
        }

        // ── E2E07: Happy path is deterministic across 3 independent runs ────────────

        [Test]
        public async Task E2E07_HappyPath_IsDeterministic_AcrossThreeRuns()
        {
            async Task<(bool envReady, bool fixtureOk, bool lifecycleOk, bool diagOk, string stage)>
                RunOnce(string suffix)
            {
                string corr = $"{CorrelationBase}-e2e07-{suffix}";

                // Each run gets its own factory+client to guarantee independent state
                using SignOffFactory f = new();
                using HttpClient c = f.CreateClient();
                string jwt = await ObtainJwtAsync(c, $"e2e07-{suffix}");
                c.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);

                // Provision fixtures first so environment check reports Ready
                EnterpriseFixtureProvisionResponse fixture = await PostFixtureProvisionAsync(c, corr);

                // Now run environment check with all checks enabled
                ProtectedSignOffEnvironmentResponse env = await PostEnvironmentCheckAsync(c, corr);
                EnterpriseSignOffLifecycleResponse lifecycle = await PostLifecycleExecuteAsync(c, corr);
                ProtectedSignOffDiagnosticsResponse diag = await GetDiagnosticsAsync(c, corr);

                return (env.IsReadyForProtectedRun, fixture.IsProvisioned,
                        lifecycle.IsLifecycleVerified, diag.IsOperational,
                        lifecycle.ReachedStage.ToString());
            }

            var run1 = await RunOnce("run1");
            var run2 = await RunOnce("run2");
            var run3 = await RunOnce("run3");

            Assert.Multiple(() =>
            {
                Assert.That(run1.envReady, Is.True, "Run1: environment must be ready");
                Assert.That(run2.envReady, Is.True, "Run2: environment must be ready");
                Assert.That(run3.envReady, Is.True, "Run3: environment must be ready");

                Assert.That(run1.fixtureOk, Is.True, "Run1: fixtures must be provisioned");
                Assert.That(run2.fixtureOk, Is.True, "Run2: fixtures must be provisioned");
                Assert.That(run3.fixtureOk, Is.True, "Run3: fixtures must be provisioned");

                Assert.That(run1.lifecycleOk, Is.True, "Run1: lifecycle must be verified");
                Assert.That(run2.lifecycleOk, Is.True, "Run2: lifecycle must be verified");
                Assert.That(run3.lifecycleOk, Is.True, "Run3: lifecycle must be verified");

                Assert.That(run1.diagOk, Is.True, "Run1: diagnostics must be operational");
                Assert.That(run2.diagOk, Is.True, "Run2: diagnostics must be operational");
                Assert.That(run3.diagOk, Is.True, "Run3: diagnostics must be operational");

                Assert.That(run1.stage, Is.EqualTo("Complete"), "Run1: must reach Complete stage");
                Assert.That(run2.stage, Is.EqualTo("Complete"), "Run2: must reach Complete stage");
                Assert.That(run3.stage, Is.EqualTo("Complete"), "Run3: must reach Complete stage");
            });
        }

        // ── E2E08: Wrong-password 401 is distinguishable from backend unavailability ─

        [Test]
        public async Task E2E08_AuthFailure_WrongPassword_Returns401_NotServiceUnavailable()
        {
            using SignOffFactory factory = new();
            using HttpClient unauthClient = factory.CreateClient();

            string badLoginEmail = $"e2e08-badauth-{Guid.NewGuid():N}@biatec-e2e.example.com";

            // Register first so the user exists
            await unauthClient.PostAsJsonAsync("/api/v1/auth/register", new
            {
                Email = badLoginEmail,
                Password = "CorrectPass123!",
                ConfirmPassword = "CorrectPass123!",
                FullName = "E2E08 Auth Failure Test"
            });

            // Login with wrong password
            HttpResponseMessage loginResp = await unauthClient.PostAsJsonAsync("/api/v1/auth/login", new
            {
                Email = badLoginEmail,
                Password = "WrongPassword!"
            });

            // Must be 400 or 401 — NOT 503 (service unavailable) or 500 (internal error)
            Assert.That(
                loginResp.StatusCode == HttpStatusCode.Unauthorized ||
                loginResp.StatusCode == HttpStatusCode.BadRequest,
                Is.True,
                $"Wrong-password login must return 401/400 (distinguishable from backend unavailability). " +
                $"Got: {loginResp.StatusCode}");

            // Protected endpoints with an expired/invalid token must return 401
            unauthClient.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", "invalid.token.here");

            HttpResponseMessage protectedResp = await unauthClient.PostAsJsonAsync(
                "/api/v1/protected-sign-off/environment/check",
                new ProtectedSignOffEnvironmentRequest { CorrelationId = "e2e08" });

            Assert.That(protectedResp.StatusCode, Is.EqualTo(HttpStatusCode.Unauthorized),
                "Protected endpoint with invalid token must return 401, not 503 or 500");
        }

        // ── E2E09: Lifecycle fails with attributable stage when prerequisites absent ─
        //
        // When fixture provisioning is skipped entirely and the default issuer has no
        // members, the Initiation stage must fail with explicit guidance (not a generic crash).

        [Test]
        public async Task E2E09_LifecycleFails_WithAttributableStage_WhenMissingPrerequisites()
        {
            // Use a fresh factory with a fresh issuer that has NO pre-provisioned fixtures.
            // Unlike the normal happy-path flow which calls ProvisionFixtures first, this test
            // skips provisioning — the lifecycle service must fail at a specific stage, not crash.
            using SignOffFactory factory = new();
            using HttpClient client = factory.CreateClient();
            string jwt = await ObtainJwtAsync(client, $"e2e09-{Guid.NewGuid():N}");
            client.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);

            // Use an issuer ID that has NO pre-provisioned fixtures
            string isolatedIssuerId = $"e2e09-no-fixtures-issuer-{Guid.NewGuid():N}";
            string corr = $"{CorrelationBase}-e2e09";

            HttpResponseMessage resp = await client.PostAsJsonAsync(
                "/api/v1/protected-sign-off/lifecycle/execute",
                new EnterpriseSignOffLifecycleRequest
                {
                    CorrelationId = corr,
                    IssuerId = isolatedIssuerId,
                    ProvisionFixturesIfAbsent = false   // explicitly skip auto-provisioning
                });

            // Response must be HTTP 200 regardless of lifecycle outcome (failure is in the body)
            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK),
                "Lifecycle endpoint must return 200 even when lifecycle fails (failure is in body)");

            EnterpriseSignOffLifecycleResponse? body =
                await resp.Content.ReadFromJsonAsync<EnterpriseSignOffLifecycleResponse>();

            Assert.That(body, Is.Not.Null, "Response body must be present");

            // The lifecycle may fail (expected when issuer has no members) OR succeed
            // (the default issuer is used if the service falls back). What must NOT happen:
            // - a 500 exception
            // - IsLifecycleVerified=true while ReachedStage≠Complete
            if (!body!.IsLifecycleVerified)
            {
                Assert.That(body.ActionableGuidance, Is.Not.Null.And.Not.Empty,
                    "Failed lifecycle must have actionable guidance — operator must know what to fix");
                Assert.That(body.Stages, Is.Not.Empty,
                    "Stages list must be populated so the failing stage is identifiable");

                // At least one stage must have Failed outcome (not all Verified)
                bool anyFailed = body.Stages.Any(s => s.Outcome == LifecycleStageOutcome.Failed);
                Assert.That(anyFailed, Is.True,
                    "At least one stage must explicitly fail — failure must not be a silent gap");

                // Every failed stage must have non-null UserGuidance
                foreach (SignOffLifecycleTransition stage in body.Stages
                    .Where(s => s.Outcome == LifecycleStageOutcome.Failed))
                {
                    Assert.That(stage.UserGuidance, Is.Not.Null.And.Not.Empty,
                        $"Stage {stage.Stage} failed but has no UserGuidance — operator cannot triage");
                }
            }
        }

        // ── E2E10: Missing-config backend returns Misconfigured status (fail-closed) ─

        [Test]
        public async Task E2E10_MissingConfig_EnvironmentCheck_ReturnsMisconfigured()
        {
            // Create a factory that is missing the required JwtConfig:SecretKey
            // but otherwise has a valid startup (enough for the server to start).
            // The environment check should return Misconfigured, not Ready.
            using MisconfiguredSignOffFactory factory = new();

            // The factory may fail to start due to missing JWT config.
            // We catch startup failure as a valid fail-closed signal.
            try
            {
                using HttpClient unauthClient = factory.CreateClient();

                // Try to register+authenticate — may return 500 due to broken JWT config.
                HttpResponseMessage regResp = await unauthClient.PostAsJsonAsync(
                    "/api/v1/auth/register", new
                    {
                        Email = $"e2e10-{Guid.NewGuid():N}@biatec-e2e.example.com",
                        Password = "FailClosedTest123!",
                        ConfirmPassword = "FailClosedTest123!",
                        FullName = "E2E10 Fail Closed Test"
                    });

                // If registration succeeded (server started despite broken config), check env
                if (regResp.IsSuccessStatusCode)
                {
                    JsonDocument? regDoc = await regResp.Content.ReadFromJsonAsync<JsonDocument>();
                    string? token = regDoc?.RootElement
                        .GetProperty("accessToken").GetString();

                    if (!string.IsNullOrEmpty(token))
                    {
                        unauthClient.DefaultRequestHeaders.Authorization =
                            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                        HttpResponseMessage envResp = await unauthClient.PostAsJsonAsync(
                            "/api/v1/protected-sign-off/environment/check",
                            new ProtectedSignOffEnvironmentRequest
                            {
                                CorrelationId = "e2e10-misconfigured",
                                IncludeConfigCheck = true
                            });

                        if (envResp.IsSuccessStatusCode)
                        {
                            ProtectedSignOffEnvironmentResponse? env =
                                await envResp.Content.ReadFromJsonAsync<ProtectedSignOffEnvironmentResponse>();

                            // When config is incomplete, status must not be Ready
                            if (env != null)
                            {
                                Assert.That(env.Status,
                                    Is.Not.EqualTo(ProtectedEnvironmentStatus.Ready),
                                    "Environment with missing required config must not report Ready status");
                            }
                        }
                    }
                }
                // Server startup failure or auth failure = acceptable fail-closed behavior
            }
            catch (Exception ex) when (
                ex is InvalidOperationException ||
                ex is HttpRequestException ||
                ex.InnerException is HttpRequestException)
            {
                // Expected: misconfigured server may refuse to start or respond
                Assert.Pass(
                    $"Fail-closed behavior confirmed: server refused to start or respond " +
                    $"with missing required configuration. Exception: {ex.GetType().Name}");
            }
        }

        // ── E2E11: All 6 lifecycle stages appear in order with correct outcomes ───────

        [Test]
        public async Task E2E11_LifecycleStages_AllSixPresent_InExpectedOrder_WithVerifiedOutcome()
        {
            string corr = $"{CorrelationBase}-e2e11";
            EnterpriseSignOffLifecycleResponse resp = await PostLifecycleExecuteAsync(_client, corr);

            Assert.That(resp.IsLifecycleVerified, Is.True, "Lifecycle must be verified");
            Assert.That(resp.Stages.Count, Is.EqualTo(6),
                "Exactly 6 stages expected in the happy path");

            SignOffLifecycleStage[] expectedOrder =
            {
                SignOffLifecycleStage.Authentication,
                SignOffLifecycleStage.Initiation,
                SignOffLifecycleStage.StatusPolling,
                SignOffLifecycleStage.TerminalState,
                SignOffLifecycleStage.Validation,
                SignOffLifecycleStage.Complete
            };

            for (int i = 0; i < expectedOrder.Length; i++)
            {
                Assert.That(resp.Stages[i].Stage, Is.EqualTo(expectedOrder[i]),
                    $"Stage at position {i} must be {expectedOrder[i]}");
                Assert.That(resp.Stages[i].Outcome, Is.EqualTo(LifecycleStageOutcome.Verified),
                    $"Stage {expectedOrder[i]} must be Verified in the happy path");
            }
        }

        // ── E2E12: Verified stages have null UserGuidance (clean evidence) ────────────

        [Test]
        public async Task E2E12_VerifiedStages_HaveNullUserGuidance_CleanEvidence()
        {
            string corr = $"{CorrelationBase}-e2e12";
            EnterpriseSignOffLifecycleResponse resp = await PostLifecycleExecuteAsync(_client, corr);

            Assert.That(resp.IsLifecycleVerified, Is.True, "Lifecycle must be verified");

            foreach (SignOffLifecycleTransition stage in resp.Stages
                .Where(s => s.Outcome == LifecycleStageOutcome.Verified))
            {
                Assert.That(stage.UserGuidance, Is.Null,
                    $"Verified stage {stage.Stage} must have null UserGuidance " +
                    $"— operator guidance in a passing stage pollutes the evidence artifact");
            }
        }

        // ── E2E13: CorrelationId is echoed across all four response objects ────────────

        [Test]
        public async Task E2E13_CorrelationId_IsEchoed_AcrossAllFourResponses()
        {
            string corr = $"{CorrelationBase}-e2e13-{Guid.NewGuid():N}";

            ProtectedSignOffEnvironmentResponse envResp = await PostEnvironmentCheckAsync(_client, corr);
            EnterpriseFixtureProvisionResponse fixtureResp = await PostFixtureProvisionAsync(_client, corr);
            EnterpriseSignOffLifecycleResponse lifecycleResp = await PostLifecycleExecuteAsync(_client, corr);
            ProtectedSignOffDiagnosticsResponse diagResp = await GetDiagnosticsAsync(_client, corr);

            Assert.Multiple(() =>
            {
                Assert.That(envResp.CorrelationId, Is.EqualTo(corr),
                    "Environment check must echo the request correlation ID");
                Assert.That(fixtureResp.CorrelationId, Is.EqualTo(corr),
                    "Fixture provision must echo the request correlation ID");
                Assert.That(lifecycleResp.CorrelationId, Is.EqualTo(corr),
                    "Lifecycle execute must echo the request correlation ID");
                Assert.That(diagResp.CorrelationId, Is.EqualTo(corr),
                    "Diagnostics must echo the request correlation ID");
            });
        }

        // ── E2E14: WorkflowGovernanceEnabled check is observable in environment check ─

        [Test]
        public async Task E2E14_EnvironmentCheck_GovernanceCheckOutcome_IsObservable()
        {
            string corr = $"{CorrelationBase}-e2e14";
            ProtectedSignOffEnvironmentResponse resp = await PostEnvironmentCheckAsync(_client, corr);

            EnvironmentCheck? govCheck = resp.Checks
                .FirstOrDefault(c => c.Name == "WorkflowGovernanceEnabled");

            Assert.That(govCheck, Is.Not.Null,
                "WorkflowGovernanceEnabled check must be present when IncludeConfigCheck=true");
            Assert.That(govCheck!.Outcome, Is.EqualTo(EnvironmentCheckOutcome.Pass).Or
                .EqualTo(EnvironmentCheckOutcome.DegradedFail),
                "Governance check must produce a specific, non-Unknown outcome — not hardcoded");
        }

        // ── E2E15: Full journey independently repeatable (concurrent users, no shared state) ─

        [Test]
        public async Task E2E15_FullJourney_IsIndependentlyRepeatable_ConcurrentUsers()
        {
            // Launch two parallel users and verify each gets independent results
            Task<(bool lifecycleOk, string stage, string corrId)> RunUser(string userTag) =>
                Task.Run(async () =>
                {
                    string corr = $"{CorrelationBase}-e2e15-{userTag}-{Guid.NewGuid():N}";
                    using SignOffFactory f = new();
                    using HttpClient c = f.CreateClient();
                    string jwt = await ObtainJwtAsync(c, userTag);
                    c.DefaultRequestHeaders.Authorization =
                        new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);

                    EnterpriseSignOffLifecycleResponse lifecycle =
                        await PostLifecycleExecuteAsync(c, corr);

                    return (lifecycle.IsLifecycleVerified, lifecycle.ReachedStage.ToString(), corr);
                });

            var (ok1, stage1, corr1) = await RunUser("user-a");
            var (ok2, stage2, corr2) = await RunUser("user-b");

            Assert.Multiple(() =>
            {
                Assert.That(ok1, Is.True, "User A lifecycle must succeed independently");
                Assert.That(ok2, Is.True, "User B lifecycle must succeed independently");
                Assert.That(stage1, Is.EqualTo("Complete"), "User A must reach Complete");
                Assert.That(stage2, Is.EqualTo("Complete"), "User B must reach Complete");
                Assert.That(corr1, Is.Not.EqualTo(corr2),
                    "Correlation IDs must be unique per user");
            });
        }

        // ── E2E16: Fixture reset produces a consistent provisioned issuer ─────────────

        [Test]
        public async Task E2E16_FixtureReset_ProducesConsistentProvisionedIssuer()
        {
            string corr = $"{CorrelationBase}-e2e16-{Guid.NewGuid():N}";

            // First provision
            EnterpriseFixtureProvisionResponse first = await PostFixtureProvisionAsync(_client, corr + "-first");
            Assert.That(first.IsProvisioned, Is.True, "First fixture provision must succeed");

            // Reset (ResetIfExists=true)
            EnterpriseFixtureProvisionResponse reset = await PostFixtureProvisionAsync(_client, corr + "-reset");
            Assert.That(reset.IsProvisioned, Is.True, "Fixture provision after reset must succeed");
            Assert.That(reset.IssuerId, Is.EqualTo(first.IssuerId),
                "IssuerId must be stable across reset — same protected tenant");
        }

        // ── E2E17: Environment check without fixture provision shows degraded fixture check ─

        [Test]
        public async Task E2E17_EnvironmentCheck_WithoutFixtureProvision_ShowsFixtureStatus()
        {
            // Fresh factory — no fixtures provisioned
            using SignOffFactory freshFactory = new();
            using HttpClient freshClient = freshFactory.CreateClient();
            string freshJwt = await ObtainJwtAsync(freshClient, $"e2e17-{Guid.NewGuid():N}");
            freshClient.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", freshJwt);

            // Request environment check including fixture check
            HttpResponseMessage resp = await freshClient.PostAsJsonAsync(
                "/api/v1/protected-sign-off/environment/check",
                new ProtectedSignOffEnvironmentRequest
                {
                    CorrelationId = $"{CorrelationBase}-e2e17",
                    IncludeConfigCheck = true,
                    IncludeFixtureCheck = true
                });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

            ProtectedSignOffEnvironmentResponse? body =
                await resp.Content.ReadFromJsonAsync<ProtectedSignOffEnvironmentResponse>();
            Assert.That(body, Is.Not.Null);

            // There must be a fixture-related check in the response
            EnvironmentCheck? fixtureCheck = body!.Checks
                .FirstOrDefault(c => c.Category == EnvironmentCheckCategory.EnterpriseFixtures);
            Assert.That(fixtureCheck, Is.Not.Null,
                "When IncludeFixtureCheck=true, an EnterpriseFixtures category check must be present");

            // The environment status must be deterministic (either Ready or Degraded — never Unknown)
            Assert.That(body.Status,
                Is.EqualTo(ProtectedEnvironmentStatus.Ready)
                .Or.EqualTo(ProtectedEnvironmentStatus.Degraded)
                .Or.EqualTo(ProtectedEnvironmentStatus.Misconfigured),
                "Environment status must be a concrete value, not Unknown");
        }

        // ── E2E18: Lifecycle verify evidence fields — all stages have non-null outcomes ─

        [Test]
        public async Task E2E18_LifecycleExecute_AllStages_HaveNonNullOutcomes()
        {
            string corr = $"{CorrelationBase}-e2e18-{Guid.NewGuid():N}";

            EnterpriseSignOffLifecycleResponse resp = await PostLifecycleExecuteAsync(_client, corr);

            Assert.That(resp.Stages, Is.Not.Null.And.Not.Empty,
                "Lifecycle stages list must not be empty");

            foreach (SignOffLifecycleTransition stage in resp.Stages)
            {
                Assert.That(stage.Stage.ToString(), Is.Not.Null.And.Not.Empty,
                    $"Stage name must not be null or empty");
                Assert.That(stage.Outcome,
                    Is.EqualTo(LifecycleStageOutcome.Verified).Or
                    .EqualTo(LifecycleStageOutcome.Skipped).Or
                    .EqualTo(LifecycleStageOutcome.Failed),
                    $"Stage {stage.Stage} outcome must be a concrete enum value, not default");
            }
        }

        // ── E2E19: Diagnostics distinguishes configuration vs service failures ─────────

        [Test]
        public async Task E2E19_Diagnostics_DistinguishesConfigurationAndServiceFailures()
        {
            string corr = $"{CorrelationBase}-e2e19-{Guid.NewGuid():N}";

            ProtectedSignOffDiagnosticsResponse diag = await GetDiagnosticsAsync(_client, corr);

            // FailureCategories must be present and structured
            Assert.That(diag.FailureCategories, Is.Not.Null,
                "Diagnostics must always return a FailureCategories object");

            // In a well-configured factory, there should be no configuration failure
            Assert.That(diag.FailureCategories.HasConfigurationFailure, Is.False,
                "A properly configured factory must not report configuration failures");

            // IsOperational must be true in a well-configured environment
            Assert.That(diag.IsOperational, Is.True,
                "Diagnostics must report IsOperational=true when the backend is correctly configured");
        }

        // ── E2E20: Release gate evidence — IsLifecycleVerified=true is the gate predicate ─
        //
        // This is the key predicate that the Tier 2 CI workflow checks in Step I
        // (Enforce lifecycle pass).  Any code change that makes this return false
        // for a well-configured environment would break the release gate.

        [Test]
        public async Task E2E20_ReleaseGatePredicate_IsLifecycleVerified_TrueForWellConfiguredEnv()
        {
            // Run the full happy path and assert the exact predicate that the workflow gate checks
            string corr = $"{CorrelationBase}-e2e20-{Guid.NewGuid():N}";

            // Provision fixtures (ensures issuer is ready)
            EnterpriseFixtureProvisionResponse fixture = await PostFixtureProvisionAsync(_client, corr);
            Assert.That(fixture.IsProvisioned, Is.True, "Prerequisites: fixtures must provision");

            // Execute lifecycle
            EnterpriseSignOffLifecycleResponse lifecycle = await PostLifecycleExecuteAsync(_client, corr);

            // THE GATE PREDICATE — this is exactly what Step I in protected-sign-off.yml checks:
            //   if [ "$LIFECYCLE_OK" != "true" ]; then exit 1; fi
            Assert.That(lifecycle.IsLifecycleVerified, Is.True,
                "IsLifecycleVerified must be true for a well-configured environment. " +
                "This is the exact predicate used by the Tier 2 CI release gate enforcement step. " +
                "A false value here means the workflow would fail at Step I and refuse to award " +
                "release gate credit, even when all other checks pass.");

            Assert.That(lifecycle.ReachedStage.ToString(), Is.EqualTo("Complete"),
                "ReachedStage must be Complete — the release gate requires full lifecycle completion");

            Assert.That(lifecycle.FailedStageCount, Is.EqualTo(0),
                "No stages must fail in a well-configured environment");
        }

        // ── HTTP helpers ────────────────────────────────────────────────────────────────

        private static async Task<string> ObtainJwtAsync(HttpClient client, string userTag)
        {
            string email = $"e2e-signoff-{userTag}@biatec-e2e.example.com";
            HttpResponseMessage resp = await client.PostAsJsonAsync("/api/v1/auth/register", new
            {
                Email = email,
                Password = "ProtectedSignOff!E2E",
                ConfirmPassword = "ProtectedSignOff!E2E",
                FullName = $"E2E Protected Sign-Off User ({userTag})"
            });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK)
                .Or.EqualTo(HttpStatusCode.Created),
                $"Registration must succeed for test user '{userTag}'. Status: {resp.StatusCode}");

            JsonDocument? doc = await resp.Content.ReadFromJsonAsync<JsonDocument>();
            string? token = doc?.RootElement.GetProperty("accessToken").GetString();
            Assert.That(token, Is.Not.Null.And.Not.Empty,
                $"Registration must return a non-empty accessToken for user '{userTag}'");
            return token!;
        }

        private static async Task<ProtectedSignOffEnvironmentResponse> PostEnvironmentCheckAsync(
            HttpClient client, string correlationId)
        {
            HttpResponseMessage resp = await client.PostAsJsonAsync(
                "/api/v1/protected-sign-off/environment/check",
                new ProtectedSignOffEnvironmentRequest
                {
                    CorrelationId = correlationId,
                    IncludeConfigCheck = true,
                    IncludeFixtureCheck = true,
                    IncludeObservabilityCheck = true
                });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK),
                $"Environment check must return 200. Status: {resp.StatusCode}");

            ProtectedSignOffEnvironmentResponse? body =
                await resp.Content.ReadFromJsonAsync<ProtectedSignOffEnvironmentResponse>();
            Assert.That(body, Is.Not.Null, "Environment check response body must not be null");
            return body!;
        }

        private static async Task<EnterpriseFixtureProvisionResponse> PostFixtureProvisionAsync(
            HttpClient client, string correlationId)
        {
            HttpResponseMessage resp = await client.PostAsJsonAsync(
                "/api/v1/protected-sign-off/fixtures/provision",
                new EnterpriseFixtureProvisionRequest
                {
                    CorrelationId = correlationId,
                    ResetIfExists = false
                });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK),
                $"Fixture provision must return 200. Status: {resp.StatusCode}");

            EnterpriseFixtureProvisionResponse? body =
                await resp.Content.ReadFromJsonAsync<EnterpriseFixtureProvisionResponse>();
            Assert.That(body, Is.Not.Null, "Fixture provision response body must not be null");
            return body!;
        }

        private static async Task<EnterpriseSignOffLifecycleResponse> PostLifecycleExecuteAsync(
            HttpClient client, string correlationId)
        {
            HttpResponseMessage resp = await client.PostAsJsonAsync(
                "/api/v1/protected-sign-off/lifecycle/execute",
                new EnterpriseSignOffLifecycleRequest { CorrelationId = correlationId });

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK),
                $"Lifecycle execute must return 200. Status: {resp.StatusCode}");

            EnterpriseSignOffLifecycleResponse? body =
                await resp.Content.ReadFromJsonAsync<EnterpriseSignOffLifecycleResponse>();
            Assert.That(body, Is.Not.Null, "Lifecycle execute response body must not be null");
            return body!;
        }

        private static async Task<ProtectedSignOffDiagnosticsResponse> GetDiagnosticsAsync(
            HttpClient client, string correlationId)
        {
            // correlationId is controlled test data (Guid-based) — URL encoding is sufficient here.
            // Production code must use LoggingHelper.SanitizeLogInput() for any user-supplied input.
            HttpResponseMessage resp = await client.GetAsync(
                $"/api/v1/protected-sign-off/diagnostics?correlationId={Uri.EscapeDataString(correlationId)}");

            Assert.That(resp.StatusCode, Is.EqualTo(HttpStatusCode.OK),
                $"Diagnostics must return 200. Status: {resp.StatusCode}");

            ProtectedSignOffDiagnosticsResponse? body =
                await resp.Content.ReadFromJsonAsync<ProtectedSignOffDiagnosticsResponse>();
            Assert.That(body, Is.Not.Null, "Diagnostics response body must not be null");
            return body!;
        }

        // ── WebApplicationFactory specializations ──────────────────────────────────────

        /// <summary>
        /// Factory replicating the protected Tier 2 CI environment:
        /// real JWT secret + real App:Account + all required ancillary config.
        /// JwtConfig:SecretKey is owned here (never injected from an env var) to prevent
        /// the JWT key-mismatch documented in PROTECTED_SIGN_OFF_RUNBOOK.md.
        /// </summary>
        private sealed class SignOffFactory : WebApplicationFactory<BiatecTokensApi.Program>
        {
            protected override void ConfigureWebHost(IWebHostBuilder builder)
            {
                builder.ConfigureAppConfiguration((_, config) =>
                {
                    config.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        ["JwtConfig:SecretKey"] = "ProtectedSignOffE2ETestSecretKey32CharsMin",
                        ["JwtConfig:Issuer"] = "BiatecTokensApi",
                        ["JwtConfig:Audience"] = "BiatecTokensUsers",
                        ["JwtConfig:AccessTokenExpirationMinutes"] = "60",
                        ["JwtConfig:RefreshTokenExpirationDays"] = "30",
                        ["JwtConfig:ValidateIssuer"] = "true",
                        ["JwtConfig:ValidateAudience"] = "true",
                        ["JwtConfig:ValidateLifetime"] = "true",
                        ["JwtConfig:ValidateIssuerSigningKey"] = "true",
                        ["App:Account"] = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
                        ["KeyManagementConfig:Provider"] = "Hardcoded",
                        ["KeyManagementConfig:HardcodedKey"] = "ProtectedSignOffE2ETestKeyXXXXXX32Chars",
                        ["AlgorandAuthentication:Realm"] = "BiatecTokens#ARC14",
                        ["AlgorandAuthentication:CheckExpiration"] = "false",
                        ["AlgorandAuthentication:Debug"] = "true",
                        ["AlgorandAuthentication:EmptySuccessOnFailure"] = "true",
                        ["AlgorandAuthentication:AllowedNetworks:wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=:Server"] = "https://mainnet-api.4160.nodely.dev",
                        ["AlgorandAuthentication:AllowedNetworks:wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=:Token"] = "",
                        ["AlgorandAuthentication:AllowedNetworks:wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=:Header"] = "",
                        ["ProtectedSignOff:EnvironmentLabel"] = "in-process-e2e",
                        ["ProtectedSignOff:EnforceConfigGuards"] = "true",
                        ["WorkflowGovernanceConfig:Enabled"] = "true",
                        ["IPFSConfig:ApiUrl"] = "https://ipfs-api.biatec.io",
                        ["IPFSConfig:GatewayUrl"] = "https://ipfs.biatec.io/ipfs",
                        ["IPFSConfig:TimeoutSeconds"] = "30",
                        ["IPFSConfig:MaxFileSizeBytes"] = "10485760",
                        ["IPFSConfig:ValidateContentHash"] = "true",
                        ["EVMChains:0:RpcUrl"] = "https://mainnet.base.org",
                        ["EVMChains:0:ChainId"] = "8453",
                        ["EVMChains:0:GasLimit"] = "4500000",
                        ["Cors:0"] = "https://tokens.biatec.io"
                    });
                });
            }
        }

        /// <summary>
        /// Factory that intentionally omits required JwtConfig and App:Account,
        /// used to verify fail-closed behavior when configuration is incomplete.
        /// </summary>
        private sealed class MisconfiguredSignOffFactory : WebApplicationFactory<BiatecTokensApi.Program>
        {
            protected override void ConfigureWebHost(IWebHostBuilder builder)
            {
                builder.ConfigureAppConfiguration((_, config) =>
                {
                    // Deliberately missing JwtConfig:SecretKey and App:Account
                    config.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        ["KeyManagementConfig:Provider"] = "Hardcoded",
                        ["KeyManagementConfig:HardcodedKey"] = "MisconfiguredE2ETestKeyXXXXXX32Chars",
                        ["AlgorandAuthentication:Realm"] = "BiatecTokens#ARC14",
                        ["AlgorandAuthentication:CheckExpiration"] = "false",
                        ["AlgorandAuthentication:Debug"] = "true",
                        ["AlgorandAuthentication:EmptySuccessOnFailure"] = "true",
                        ["Cors:0"] = "https://tokens.biatec.io"
                    });
                });
            }
        }
    }
}
